### ISSUE TITLE
SSR problems

### ISSUE THREAD

**Issue by jas777** [ElemeFE/element-react#888]
### Description

Hello,
I was trying to use ElementUI with `react-express-views` and when I'm trying to use Button (or any other component) I get an error

### Reproduce Steps

1. Set up express server with `express-react-views`
```js
const express     = require('express');
const consoleUtil = require('../util/consoleUtil.js');

const app = express();

app.set('views', __dirname + '/views');
app.set('view-engine', 'jsx');
app.engine('jsx', require('express-react-views').createEngine());

const router = express.Router();
app.use('/', router);

router.get('/', (req, res, next) => {
    res.render('main/test.jsx', {
        test: 'test text',
        title: 'test title'
    });
});

app.listen(8080, () => {
    consoleUtil.log('Webserver running...')
});
```
2. Make `test.jsx` template in `views` folder
```js
const React     = require('react');
const ElementUI = require('element-react');

class TestLayout extends React.Component {
    render() {
        return (
            <html>
            <head>
                
            </head>
            <body>
                <ElementUI.Button>
                    Hello
                </ElementUI.Button>
            </body>
            </html>
        );
    }
}

module.exports = TestLayout;
```
3. Run the server and go to `localhost:8080`

### Error Trace (if possible)

```js
ReferenceError: document is not defined
    at Object.<anonymous> (/home/jas777/Venom/node_modules/element-react/dist/npm/es5/src/table/TableHeader.js:45:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jas777/Venom/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/jas777/Venom/node_modules/element-react/dist/npm/es5/src/table/Table.js:37:20)
```

### Solution

No idea

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by luisaddor** [comment]
same problem here

**Comment by tlecreate** [comment]
Me too

**Comment by ondrejrohon** [comment]
this issue is still present in 1.4.33 :/

**Comment by n8tb1t** [comment]
Just use wrapper of some sort:

use it like this:
```jsx
import { Table, Pagination, Loading } from './wrapper'
```

this will only import the modules you need and also, remove all the others during the build
with `tree-shaking` so the final package size will be much less.

The code needs refactoring, but it works.

Just un-comment the required components in the `wrapper` file.

`wrapper.jsx`

```jsx
import React from 'react'

const SSR = () => <div>SSR</div>

let Alert = SSR
let Button = SSR
let Card = SSR
let Layout = SSR
let Loading = SSR
let Message = SSR
let MessageBox = SSR
let Notification = SSR
let Radio = SSR
let Dialog = SSR
let Rate = SSR
let Progress = SSR
let Badge = SSR
let Tabs = SSR
let Tree = SSR
let Input = SSR
let Icon = SSR
let Menu = SSR
let Steps = SSR
let Breadcrumb = SSR
let Tooltip = SSR
let InputNumber = SSR
let Checkbox = SSR
let Slider = SSR
let Table = SSR
let Switch = SSR
let Form = SSR
let Upload = SSR
let Tag = SSR
let Select = SSR
let Dropdown = SSR
let Popover = SSR
let Pagination = SSR
let AutoComplete = SSR
let TimeSelect = SSR
let TimePicker = SSR
let TimeRangePicker = SSR
let DatePicker = SSR
let DateRangePicker = SSR
let Carousel = SSR
let Collapse = SSR
let ColorPicker = SSR
let Cascader = SSR
let Transfer = SSR

if (typeof window !== `undefined`) {
  // Alert = require('element-react/next').Alert
  // Button = require('element-react/next').Button
  // Card = require('element-react/next').Card
  // Layout = require('element-react/next').Layout
  // Loading = require('element-react/dist/npm/es6/src/loading').Loading
  Loading = require('element-react/dist/npm/es6/src/loading').default
  // Message = require('element-react/next').Message
  // MessageBox = require('element-react/next').MessageBox
  // Notification = require('element-react/next').Notification
  // Radio = require('element-react/next').Radio
  // Dialog = require('element-react/next').Dialog
  // Rate = require('element-react/next').Rate
  // Progress = require('element-react/next').Progress
  // Badge = require('element-react/next').Badge
  // Tabs = require('element-react/next').Tabs
  // Tree = require('element-react/next').Tree
  // Input = require('element-react/next').Input
  // Icon = require('element-react/next').Icon
  // Menu = require('element-react/next').Menu
  // Steps = require('element-react/next').Steps
  // Breadcrumb = require('element-react/next').Breadcrumb
  // Tooltip = require('element-react/next').Tooltip
  // InputNumber = require('element-react/next').InputNumber
  // Checkbox = require('element-react/next').Checkbox
  // Slider = require('element-react/next').Slider
  // Table = require('element-react/next').Table
  Table = require('element-react/dist/npm/es6/src/table').default
  // Switch = require('element-react/next').Switch
  // Form = require('element-react/next').Form
  // Upload = require('element-react/next').Upload
  // Tag = require('element-react/next').Tag
  // Select = require('element-react/next').Select
  // Dropdown = require('element-react/next').Dropdown
  // Popover = require('element-react/next').Popover
  Pagination = require('element-react/dist/npm/es6/src/pagination').default
  // Pagination = require('element-react/next').Pagination
  // AutoComplete = require('element-react/next').AutoComplete
  // TimeSelect = require('element-react/next').TimeSelect
  // TimePicker = require('element-react/next').TimePicker
  // TimeRangePicker = require('element-react/next').TimeRangePicker
  // DatePicker = require('element-react/next').DatePicker
  // DateRangePicker = require('element-react/next').DateRangePicker
  // Carousel = require('element-react/next').Carousel
  // Collapse = require('element-react/next').Collapse
  // ColorPicker = require('element-react/next').ColorPicker
  // Cascader = require('element-react/next').Cascader
  // Transfer = require('element-react/next').Transfer
}

export {
  Alert,
  Button,
  Card,
  Layout,
  Loading,
  Message,
  MessageBox,
  Notification,
  Radio,
  Dialog,
  Rate,
  Progress,
  Badge,
  Tabs,
  Tree,
  Input,
  Icon,
  Menu,
  Steps,
  Breadcrumb,
  Tooltip,
  InputNumber,
  Checkbox,
  Slider,
  Table,
  Switch,
  Form,
  Upload,
  Tag,
  Select,
  Dropdown,
  Popover,
  Pagination,
  AutoComplete,
  TimeSelect,
  TimePicker,
  TimeRangePicker,
  DatePicker,
  DateRangePicker,
  Carousel,
  Collapse,
  ColorPicker,
  Cascader,
  Transfer
}
```

**Comment by Jezfx** [comment]
Cheers @n8tb1t 
Ended up using a similar solution together with [loadable](https://github.com/smooth-code/loadable-components) to work with a Gatsby project.

```js
Button = loadable((): any => import("element-react/dist/npm/es6/src/button"))
```

This did give me import issues when testing with Jest. However, managed to get around it by setting the `moduleNameMapper` to load `element-react` instead


```js
moduleNameMapper: {
 "src/components/wrapper": "element-react",
}

```
